version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_proxy
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    labels:
      - "com.github.nginx-proxy.nginx"
    networks:
      - wordpress_external

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: ${COMPOSE_PROJECT_NAME}_acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${ADMIN_EMAIL}
      - NGINX_PROXY_CONTAINER=${COMPOSE_PROJECT_NAME}_nginx_proxy
    depends_on:
      - nginx-proxy

  wordpress:
    image: wordpress:latest
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    expose:
      - "${WORDPRESS_PORT}"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes:rw
      - ./wp-content/plugins:/var/www/html/wp-content/plugins:rw
      - ./wp-content/uploads:/var/www/html/wp-content/uploads:rw
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - WORDPRESS_DB_HOST=${DB_HOST}:${DB_PORT}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
      - WORDPRESS_DEBUG=${WP_DEBUG}
      - WORDPRESS_CONFIG_EXTRA=|
          define('WP_HOME', '${WP_HOME}');
          define('WP_SITEURL', '${WP_SITEURL}');
          define('FS_METHOD', '${FS_METHOD}');
      - WORDPRESS_AUTH_KEY=${WP_AUTH_KEY}
      - WORDPRESS_SECURE_AUTH_KEY=${WP_SECURE_AUTH_KEY}
      - WORDPRESS_LOGGED_IN_KEY=${WP_LOGGED_IN_KEY}
      - WORDPRESS_NONCE_KEY=${WP_NONCE_KEY}
      - WORDPRESS_AUTH_SALT=${WP_AUTH_SALT}
      - WORDPRESS_SECURE_AUTH_SALT=${WP_SECURE_AUTH_SALT}
      - WORDPRESS_LOGGED_IN_SALT=${WP_LOGGED_IN_SALT}
      - WORDPRESS_NONCE_SALT=${WP_NONCE_SALT}
    networks:
      - wordpress_external
    depends_on:
      - nginx-proxy

volumes:
  wordpress_data:
  certs:
  vhost:
  html:
  acme:

networks:
  wordpress_external:
    driver: bridge